Lucien/copyright target elem
geops/mobility-toolbox-js pull request #78
Opened 2020-11-25 08:47 UTC by edellucien

# How to

 - Optional parameter 'targetElement' added to the copyright control.
# Others

- [ ] It's not a hack or at least an unauthorized hack :).
- [ ] The images added are optimized.
- [ ] Everything in ticket description has been fixed.
- [ ] The author of the MR has made its own review before assigning the reviewer.
- [ ] The title means something for a human being.
- [ ] The title contains [WIP] if it's necessary.
- [ ] Labels applied. if it's a release? a hotfix?
- [ ] The new class' members & methods are well documented
- [ ] Tests added.

2020-11-25 09:12 UTC, edellucien commented on src/common/controls/Control.js
> +    this.targetElement = options.targetElement || this.map.getTargetElement();
Do you agree on setting the map target element as default target for the copyright?

2020-11-25 09:12 UTC, edellucien commented on src/ol/Map.js
> +// import CopyrightControl from './controls/Copyright';
Do we actually still want to set CopyrightControl as default like this?

2020-11-25 09:17 UTC, edellucien commented on src/doc/examples/ol-copyright.js
> +  // later, you can remove the control
We could think of a button to remove the copyright. In order to show how to do it.

2020-11-25 10:09 UTC, mhaertwig requested changes

2020-11-25 10:09 UTC, mhaertwig commented on src/common/controls/Control.js
> +    this.targetElement = options.targetElement || this.map.getTargetElement();
`getTargetElement()` only works for OpenLayers maps, not for a mapbox map. So, please remove everything behind the `||` and put `this.target = options.targetElement` in the constructor of the mixin.

2020-11-25 10:09 UTC, mhaertwig commented on src/common/controls/mixins/Copyright.js
> -      this.target = target;
Do `this.target = this.target || target`;

2020-11-25 13:57 UTC, edellucien commented
Code adapted as you wished

2020-11-25 14:11 UTC, mhaertwig requested changes

2020-11-25 14:11 UTC, mhaertwig commented on src/common/controls/Control.js
> +    this.target = options.targetElement;
Please remove both lines in this file (see next comment).

2020-11-25 14:11 UTC, mhaertwig commented on src/common/controls/mixins/Copyright.js
> +      this.target = this.target || target;
Do `this.target = this.options.targetElement || target`.

2020-11-25 14:11 UTC, mhaertwig commented on src/ol/controls/Copyright.js
> +    this.addCopyrightContainer();
The original one was correct. You have to pass the container as a function.

2020-11-25 16:53 UTC, edellucien commented on src/common/controls/mixins/Copyright.js
> +/* eslint-disable no-useless-constructor */
```suggestion
```

2020-11-30 14:22 UTC, oterral approved these changes
lgtm

2020-11-30 14:22 UTC, merged